name: southeastcc
favicon: null
layout_spectrum: 0.78874
typography_spectrum: 0.21367
title: SoutheastCC in Denver
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fafafa'
    - '#58585a'
    - '#969799'
    - '#1bbdca'
    - '#e46e26'
  brandStrength: 0.1875
  lightness: 0.5625
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
