name: southeastcc
favicon: null
layout_spectrum: 0.48303
typography_spectrum: 0.5438
title: Southeast Christian Church
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2b2c30'
    - '#fefefe'
    - '#5a5e61'
    - '#16bbc7'
    - '#b2b3b4'
  brandStrength: 0.125
  lightness: 0.5625
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
